### ISSUE TITLE
Incompatibility with corslite.js

### ISSUE THREAD

**Issue by constantm** [pretenderjs/pretender#112]
After a mighty journey starting from `ember-mapbox-cli`, heading through to `ember-mirage-cli` I finally ended up here. Hurray!

So, it looks like the fake `XMLHttpRequest` object that gets created by Pretender doesn't include the property `withCredentials`, which corslite.js uses to detect whether we're on IE or not. Problem occurs here: https://github.com/mapbox/corslite/blob/master/corslite.js#L20

It then proceeds to call `x = new window.XDomainRequest();`, which breaks because we're not actually on IE.

**Comment by jfirebaugh** [comment]
Hi, corslite maintainer here. A `withCredentials` check is the [widely accepted means of feature-detecting CORS support](http://stackoverflow.com/questions/1641507/detect-browser-support-for-cross-domain-xmlhttprequests). I would strongly encourage a fix in Pretender here; corslite is probably far from the only affected library or code.

**Comment by kturney** [comment]
this should have been fixed by https://github.com/pretenderjs/FakeXMLHttpRequest/pull/12

**Comment by stefanpenner** [comment]
@kturney thanks, I believe you are correct.

Closing, but if the issue persists please provide a re-production and we can reopen.

**Comment by allthesignals** [comment]
I think this is happening to me with fake_xml_http_request (see my detailed issue here https://github.com/samselikoff/ember-cli-mirage/issues/1320). cc @jfirebaugh; not sure where the problem is coming from. I'm upgraded to pretenderjs 2.0 from 1.6, same issue applies.
