### ISSUE TITLE
HTTP request recording/playback (similar to VCR).

### ISSUE THREAD

**Issue by paulot** [pretenderjs/pretender#125]
A really cool feature to add would be HTTP request recording/playback like in nock (https://github.com/pgte/nock). This would save a lot of the pain from keeping mocks updated, as test runs could simply record the requests and play them back on subsequent runs.

**Comment by trek** [comment]
This would indeed be a useful feature, but doesn't represent an issue. We'd consider this if someone posted a PR or a more detailed plan for how to implement this.
