### ISSUE TITLE
PretenderJs can't parse array query Parameters

### ISSUE THREAD

**Issue by olivierlesnicki** [pretenderjs/pretender#135]
`/api/secure/meters?accountNumber=1&accountNumber=2`
Results in request.queryParams.accountNumber being equal to 2 instead of [1, 2]. Please note, this is a standard way (old) of passing "array of values" in queryParameters.

Some back-end API frameworks do not support:
`/api/secure/meters?accountNumber[]=1&accountNumber[]=2`

**Comment by john-kurkowski** [comment]
This is an issue in an underlying library. See tildeio/route-recognizer#73.
