### ISSUE TITLE
Support OPTIONS request

### ISSUE THREAD

**Issue by tsteuwer** [pretenderjs/pretender#136]
It would be really great if we can add support for an ``OPTIONS`` request. If no one picks this up, I'll see what I can do.

**Comment by riklaunim** [comment]
what's missing for options support? I see some support in the code, maybe with one thing missing: https://github.com/riklaunim/pretender/commit/9e9fcba0c8f6bbe6a8c596da8055640d9d16c728 but still somewhere something isn't there as I'm trying to add options mocking support to ember-cli-mirrage

**Comment by trek** [comment]
`OPTIONS` requests have been supported since 0.8.0 from this commit: https://github.com/pretenderjs/pretender/commit/61c8f288d5da5643d931b738c8e47dae8fef4309
