### ISSUE TITLE
Reasons a request would not be handled?

### ISSUE THREAD

**Issue by mattmcginnis** [pretenderjs/pretender#146]
I have an xhr request in a custom authenticator using ember-simple-auth that doesn't get handled by pretender in tests.  All of my other api calls get handled with no problems.  No hooks for this request get called including unhandledRequest.  The result is simply a 404 which causes tests to intermittently fail due to the 404 sometimes taking up to 3 seconds.  

Any ideas about what might be causing this would be greatly appreciated.

**Comment by trek** [comment]
If I had to guess, I'd say `ember-simple-auth` is grabbing a reference to `XMLHttpRequest` before Pretender gets a chance to replace it. Can you isolate this to a test case or example application I can inspect?

**Comment by mattmcginnis** [comment]
Sorry, this is a bit old and I forgot about posting the issue.  It has since been resolved (but I don't remember what fixed it)
