### ISSUE TITLE
importing Pretender with transpiled es6 fails appearsBrowserified test

### ISSUE THREAD

**Issue by mattgrannary** [pretenderjs/pretender#152]
My test suite is transpiled from es6 using babel and I wanted to import Pretender. Calling `import Pretender from 'pretender'` and instantiating a Pretender object gave me the error:

```
TypeError: FakeXMLHttpRequest is not a function
      at interceptor (node_modules/pretender/pretender.js:119:15)
      at Object.Pretender (node_modules/pretender/pretender.js:102:25)
      at Context.<anonymous> (api-test.js:16:14)
```

I've tracked down the issue to the check for `appearsBrowserified` at the beginning of the closure in pretender.js. The final condition checks if the process is an `[object Object]` but if I console out `Object.prototype.toString.call(process)` I get `[object process]`.

I'm running node 5.5.0 with pretender 1.1.0. Is Pretender compatible with newer node versions?

**Comment by NullVoxPopuli** [comment]
I'm getting a similar issue:
```
 TypeError: FakeXMLHttpRequest is not a constructor
    at interceptor (project/dist/vendor/pretender/pretender.js:119:15)
```
