### ISSUE TITLE
Dependency version: route-recognizer fails on build

### ISSUE THREAD

**Issue by ryanostrom** [pretenderjs/pretender#153]
As a developer I want pretender's route-recognizer dependency in it's bower.json to upgrade from `0.1.1` to `0.1.9`.

**Given** I install pretender `1.1.0` to an Ember 2.3 project 
**When** I execute Ember build
**Then** I expect to the build to run without error
**Instead** I encounter the error described in [this thread](https://github.com/tildeio/route-recognizer/issues/44).

**Comment by ryanostrom** [comment]
#155

**Comment by trek** [comment]
Handled by https://github.com/pretenderjs/pretender/pull/163
