### ISSUE TITLE
Value of `this` in XHR Events

### ISSUE THREAD

**Issue by alexclarkofficial** [pretenderjs/pretender#158]
This might be an issue, but is probably more of a question:

Using the library the value of `this` in my event handlers is `undefined`. I was using `this.status` to check the status code that is returned, in order to fire an error handler if it's not a 2xx. With the library it looks like I can reach that value with passing the handler a `response` param and then checking `response.target.status`.

Is this the correct implementation? Should it use `call()` to provide a good value for `this`?

Thanks!

**Comment by alexclarkofficial** [comment]
It looks like this is an issue with `fake_xml_http_request`. I can submit a PR to that project if you would like.

**Comment by trek** [comment]
I'd open an Issue there. Question though: does that native implementation set a `this`? If not, we'd sadly have to match that behavior.

**Comment by alexclarkofficial** [comment]
I'm not entirely sure what you mean. Does this JSBin answer your question?
http://jsbin.com/felarepuji/edit?html,output

I've seen the same results in FF, Safari and Chrome.

**Comment by stefanpenner** [comment]
FakeXMLHTTPRequest released as v1.6.0 🎉 includes the above mentioned fix.
