### ISSUE TITLE
Can't start because self is not defined

### ISSUE THREAD

**Issue by DVLP** [pretenderjs/pretender#179]
Trying with babel-node and with regular node too.
`import Pretender from 'pretender';`
same result as
`require('pretender');`

```
\node_modules\pretender\pretender.js:433
}(self));
  ^

ReferenceError: self is not defined
    at Object.<anonymous> (\node_modules\pretender\pretender.js:433:3)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (\node_modules\babel-register\lib\node.js:156:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (mockServer.js:1:1)
```

**Comment by trek** [comment]
Pretender mocks the browser `window.FakeXMLHttpRequest` object. I'm curious what your node use is doing? Just as part of a build step?

**Comment by DVLP** [comment]
it's a very basic setup, node 
`npm install pretender`

and my server file(from some example)

import Pretender from 'pretender';

```
var PHOTOS = {
  '10': {
    id: 10,
    src: 'http://media.giphy.com/media/UdqUo8xvEcvgA/giphy.gif'
  },
  '42': {
    id: 42,
    src: 'http://media0.giphy.com/media/Ko2pyD26RdYRi/giphy.gif'
  }
};

var server = new Pretender(function(){
  this.get('/photos', function(request){
    var all =  JSON.stringify(Object.keys(PHOTOS).map(function(k){return PHOTOS[k];}));
    return [200, {'Content-Type': 'application/json'}, all];
  });

  this.get('/photos/:id', function(request){
    return [200, {'Content-Type': 'application/json'}, JSON.stringify(PHOTOS[request.params.id])];
  });
});


```

**Comment by trek** [comment]
@DVLP sorry, I should have been a bit clearer: Pretender doesn't operating inside a node runtime since it's mocking out features that are only inside various browser environments. I was asking what your use of node was. Are you using node as a build tool or did you expect Pretender to _run_ inside node?

**Comment by trek** [comment]
Closing until we get some more info.

**Comment by rantiev** [comment]
It's natural that this lib will be used in any kind of testing modules. LIke protractor. Try to connect and run it with protractor. You will get this self is not defined. As One probably will run this outside of any window context. But even with fake window contexts Jest and Protractor have you will have no self link. There should be a possibility to pass this window, self object to pretender.
