### ISSUE TITLE
LET'S PLAY WITH ASSIGNMENTS

### ISSUE THREAD

**Issue by steveklabnik** [pretenderjs/pretender#180]
I have no idea how these rules work either.

**Comment by trek** [comment]
Your problem now, bub.

**Comment by steveklabnik** [comment]
IIIIIIIIINteresting.

Go figure the docs are wrong.

**Comment by trek** [comment]
QQ: can you assign back to me?

**Comment by steveklabnik** [comment]
I cannot

**Comment by steveklabnik** [comment]
... not even if it's open

**Comment by trek** [comment]
I wonder if I mention someone @rwjblue

**Comment by EndangeredMassa** [comment]
Trek made me do it.

**Comment by trek** [comment]
So, it appears neither being mention nor chiming in allow for assignment, but opening the Issue does.

**Comment by rwjblue** [comment]
Hmm, odd.  FWIW, I just assume all issues are my fault / responsibility 😈 .

**Comment by locks** [comment]
I wanna be assigned.

**Comment by locks** [comment]
Please GitHub.
