### ISSUE TITLE
How to parse id when URL ends in .json?

### ISSUE THREAD

**Issue by andrewhavens** [pretenderjs/pretender#190]
I am defining a route for a URL that looks like this: http://example.com/some_models/123.json

``` js
this.get('some_models/:id.json', function(request) {
  // ...
});
```

The problem is that pretender is getting confused by the `.json` at the end. How can I define this route to be able to parse the `:id`?

**Comment by trek** [comment]
This is likely a question for the people at https://github.com/tildeio/route-recognizer: See https://github.com/tildeio/route-recognizer/issues/126

**Comment by nathanhammond** [comment]
Solution:

```
this.get('some_models/:id', function(request) {
  // Inspect the ID, match on `.json` for example, respond appropriately.
});
```
