### ISSUE TITLE
Running pretender with Jsdom errors + doesn't get assigned to XMLHttpRequest

### ISSUE THREAD

**Issue by JakeDluhy** [pretenderjs/pretender#191]
I'm running jsdom with pretender for my integration tests. I've discovered two problems with it. The first, possibly related to #152 I believe, is the error `TypeError: FakeXMLHttpRequest is not a constructor`. I was able to fix this by changing

``` js
var appearsBrowserified = typeof self !== 'undefined' &&
                          typeof process !== 'undefined' &&
                          Object.prototype.toString.call(process) === '[object Object]';
```

to

``` js
var appearsBrowserified = typeof self !== 'undefined' &&
                          typeof process !== 'undefined' &&
                          (Object.prototype.toString.call(process) === '[object Object]' ||
                           Object.prototype.toString.call(process) === '[object process]');
```

After that, the problem was that pretender wasn't properly attaching to XMLHttpRequest (and therefore wasn't intercepting my requests. I think the problem (which may ultimately be a jsdom problem) is that the value for `self` that gets passed in to the closure (which I understand should be `window`) is different than the global `window` for jsdom. Which means that when overriding `self.XMLHttpRequest`, `window.XMLHttpRequest` doesn't get overridden. I was able to fix this by replacing

``` js
self.XMLHttpRequest = interceptor(this, this._nativeXMLHttpRequest);
```

with

``` js
self.XMLHttpRequest = interceptor(this, this._nativeXMLHttpRequest);
if(process.env.NODE_ENV === 'test') global.XMLHttpRequest = window.XMLHttpRequest = self.XMLHttpRequest;
```

I'd be happy to submit a PR, but I'm not sure about the first solution, and the second one seems hacky. Just thought I'd see what your thoughts were on this.

**Comment by stefanpenner** [comment]
rather then testing for node `if(process.env.NODE_ENV === 'test')`, you should likely sniff for `global`. Also `window` and `self` should be the same thing, not sure why they need to be both set.

**Comment by JakeDluhy** [comment]
I think the line
```js
if(process.env.NODE_ENV === 'test') global.XMLHttpRequest = window.XMLHttpRequest = self.XMLHttpRequest;
```
was an issue with the way I was using `jsdom` and `jsdom-global`. I recently updated those libraries and my implementation, and I'm no longer seeing that problem. I still have the problem where I need to check
```js
Object.prototype.toString.call(process) === '[object process]'
```
to avoid `TypeError: FakeXMLHttpRequest is not a constructor`. Is adding that line something you would be willing to accept into source?

**Comment by JakeDluhy** [comment]
In fact I checked back all the way to Node 4.8.4 and 0.12.18 and for both of them `Object.prototype.toString.call(process) === '[object process]'`.
