### ISSUE TITLE
A possible typo in README.md

### ISSUE THREAD

**Issue by gamtiq** [pretenderjs/pretender#193]
It seems there is a typo or absent example in [Error Requests](https://github.com/pretenderjs/pretender#error-requests) section of `README.md`:
> Your server will call a erroredRequest method with the HTTP verb, path, original request, and the original error object if your handler code causes an *error:*

**Comment by trek** [comment]
Sorry, I'm not quite seeing it. Can you elaborate?

**Comment by gamtiq** [comment]
I suppose there should be an example after the sentence or the sentence should be ended with a period (not the colon).
