### ISSUE TITLE
InvalidStateError on IE 11 when changing response type

### ISSUE THREAD

**Issue by pawepaw** [pretenderjs/pretender#196]
Hello,

I have defined route as passthrough. On ie 11 when i fire action and this route is called i got error invalidStateError when it tries to set responseType (https://github.com/pretenderjs/pretender/blob/master/pretender.js#L173)

Check microsoft bug report: https://connect.microsoft.com/IE/feedback/details/795580/ie11-xmlhttprequest-incorrectly-throws-invalidstateerror-when-setting-responsetype

Maybe you could do some workaround and fix it? Fix for this from what i have read would be to call open before you change response type.

**Comment by pawepaw** [comment]
Created PR with fix for it. https://github.com/pretenderjs/pretender/pull/197

**Comment by stefanpenner** [comment]
https://github.com/pretenderjs/pretender/pull/202
