### ISSUE TITLE
Allow paths to be regexp

### ISSUE THREAD

**Issue by airtonix** [pretenderjs/pretender#200]
So i can do this:
```es6
export const server = new Pretender();
server.get(/^((https?:)?\/\/)(.*)/, server.passThrough);
```

**Comment by DingoEatingFuzz** [comment]
Pretender uses [route-recognizer](https://github.com/tildeio/route-recognizer) for this, which has support for dynamic segments at least.

Correct me if I'm wrong, but your regex matches everything and passes through. If that's your use case, why use Pretender?

**Comment by stefanpenner** [comment]
my recommendation is to create a catchall, `server.get('/*, function() { /* custom handler to do regexp*/) )` It is unlikely for us to support both regexp and the NFA the route-recognizer users.

**Comment by airtonix** [comment]
@DingoEatingFuzz  actually it shouldn't. it only captures external urls. so urls like `/api/v2/users` should get captured by pretender.

This is actually becoming a really massive problem.

I think pretender started out with different goals than it aims for these days. Way back it was a mocking tool for frontend development, not it's a mocking tool for your unit tests. two ENTIRELY different things.

We chose pretender because it let us mock out the api before our backend team got round to the sprints and tickets that cover particular api requirements.

additionally, the library plyr.io uses ajax to load in the svg sprites... which pretender blocks.

this passthrough fiasco needs to be solved.
