### ISSUE TITLE
When importing Pretender from a webpack build, RouteRecognizer constructor lookup fails.

### ISSUE THREAD

**Issue by cowboyd** [pretenderjs/pretender#207]
When these lines run in a webpack build, https://github.com/pretenderjs/pretender/blob/master/pretender.js#L8-L9

`RouteRecognizer` and `FakeXMLHttpRequest` point to the module, not the `default` export.

Monkey patching it with this code makes it work:

```js
  RouteRecognizer = RouteRecognizer.default || RouteRecognizer;
  FakeXMLHttpRequest = FakeXMLHttpRequest.default || FakeXMLHttpRequest;
```

Not sure what the long term solution is though.

**Comment by svicalifornia** [comment]
I just submitted PR #216. My bad for not seeing #209 already fixes this, though you might prefer to merge #216, as the `getModuleDefault` function can be reused for more future `require`s.
