### ISSUE TITLE
interceptor runs into Chrome issue which causes memory leak

### ISSUE THREAD

**Issue by tonya** [pretenderjs/pretender#217]
https://github.com/pretenderjs/pretender/blob/54f98e60ba664dd489a2f969b7e981d67a419dca/pretender.js#L144

The `interceptor` is setting a function on a `FakeXMLHttpRequest` prototype which closes over instance data. This causes memory leaks, probably due to this Chrome issue: https://bugs.chromium.org/p/v8/issues/detail?id=4578

@krisselden @stefanpenner

**Comment by rwjblue** [comment]
Fixed by https://github.com/pretenderjs/pretender/pull/218
