### ISSUE TITLE
Has anyone used this with typescript?

### ISSUE THREAD

**Issue by QuantumInformation** [pretenderjs/pretender#222]
I'm trying to use pretender with typescript without the types by importing this way and forcing typescript to 
```js
let Pretender:any = require('pretender')
```

 it wraps constructors with `defaults` like:

![image](https://user-images.githubusercontent.com/216566/33841581-1d58ca94-de90-11e7-9fa6-8723be552b99.png)

If I just run it as normal

![image](https://user-images.githubusercontent.com/216566/33841620-30e1f52c-de90-11e7-8b4d-ebb8dc1b78a5.png)

this might be a webpack issue.

**Comment by QuantumInformation** [comment]
Looking at the source file, there are a bunch of require statements, which I've not seen in build files before.

![image](https://user-images.githubusercontent.com/216566/33877125-5838b32e-df1f-11e7-8ed3-7e274c6e3a62.png)

**Comment by mike-north** [comment]
I should have something for this soon. They'll be unofficial type definitions until other project maintainers can review them for accuracy and completeness

**Comment by mike-north** [comment]
@QuantumInformation I've got a PR open for adding type information to Pretender. In the meantime, the issue you're facing has less to do with TypeScript and more to do with mixing Pretender's named AMD modules with webpack (works in CommonJS modules).

If you can create a small example project with this same failure, push it to GitHub and I'll be happy to take a look at it.

**Comment by QuantumInformation** [comment]
Thx mate, I just switched our project to express and it works fine atm.
