### ISSUE TITLE
Opinion on converting the addon to ES6/Typescript?

### ISSUE THREAD

**Issue by cibernox** [pretenderjs/pretender#227]
I'd like to update pretender to work with fetch but as it is right now the codebase feels a messy (read: I'm so used to ES6 I can't even read `Pretender.prototype.` anymore).

I'm thinking that a good plan could be to add a build that compiles the sourcecode with babel (perhaps even TS). That would also make easier to accomplish any refactor with certain guarantees.

Would you favor a re-write in ES6 or TS (+ drop Phantomjs?)

**Comment by samselikoff** [comment]
I'd defer to @trek, fine by me but I haven't worked on the source. Fwiw I want to do something like this in Mirage soonish too.

**Comment by givanse** [comment]
I've opened:
> Add a build step and produce ES and CJS files. https://github.com/pretenderjs/pretender/pull/240

**Comment by givanse** [comment]
Since v3.0.1 native ES6 classes are distributed. I think this issue can be closed now.

**Comment by xg-wang** [comment]
It is distributed as ES module, but I think @cibernox also mentioned pretender source should also be written in TS/es6+
