### ISSUE TITLE
How to pass through every request in pretender?

### ISSUE THREAD

**Issue by priyanshujain** [pretenderjs/pretender#228]
I've tried `this.get("**.", this.passthrough);` but didn't worked.
How we can pass through every url requested after a bunch of uniques.
for example 

```
this.get(`${apiBaseUrl}/data/`, function(request) {
    var data = require("./data.json");
    return [200, { "Content-Type": "application/json" }, JSON.stringify(data)];
  });
  this.get("**", this.passthrough);
```
API not matching first rule should pass through to real API call, how i can do that.

**Comment by nshimiye** [comment]
@priyanshujain `this.get("*path", this.passthrough)` should work.

You can read more about `Star segments` on the [Route Recognizer Github](https://github.com/tildeio/route-recognizer)

**Comment by xg-wang** [comment]
route-recognizer and https://github.com/pretenderjs/pretender/pull/238 can pretty much support any selection need for passthrough
