### ISSUE TITLE
Import Pretender in Typescript yields empty module 

### ISSUE THREAD

**Issue by jorgelainfiesta** [pretenderjs/pretender#229]
Hi!

I'm trying to use Pretender in a Glimmer application but I'm having trouble importing the module. Using `import Pretender from 'pretender'` doesn't resolve anything because there's apparently no default export. I'm now using `import * as pretender from 'pretender'` to get the whole thing but I just get an empty object. 

I saw there's type support and tried to read the related issues (that are now closed) but I still don't know how to make it work properly.

Am I missing something? 

Thanks,
Jorge L

**Comment by marcoow** [comment]
@jorgelainfiesta: did you have a look at #223? I just had a brief look and that seems to work?

**Comment by stephanos** [comment]
I think this can be closed now, no?

**Comment by givanse** [comment]
solved with: https://github.com/pretenderjs/pretender/pull/243

**Comment by xg-wang** [comment]
Released as v3.0.1
