### ISSUE TITLE
Pretender intercepts PUT but thinks there are no handlers

### ISSUE THREAD

**Issue by joshsmith** [pretenderjs/pretender#23]
When trying to use Pretender in my tests, I keep getting an error that a `PUT` request is being unhandled.

``` bash
"Pretender intercepted PUT http://api.lvh.me:3000/passwords/4615efd359fb8d96804a1d77efea78e528667d62
but no handler was defined for this type of request"
```

But from the test below, it seems to be pretty clearly handled.

``` coffee
`import { test, moduleFor } from 'ember-qunit'`
`import startApp from '../helpers/start-app'`

App = undefined
server = undefined

module "Integration: Reset Password",
  setup: ->
    App = startApp()
    response = 
      user:
        email: "josh@coderly.com"
    server = new Pretender(->
      @put "/passwords/4615efd359fb8d96804a1d77efea78e528667d62", (request)->
        return [201, {"Content-Type": "application/json"}, JSON.stringify(response)]
    )
  teardown: ->
    Ember.run App, App.destroy
    server.shutdown()

test "Resets the password", ->
  expect 1
  visit("/passwords/4615efd359fb8d96804a1d77efea78e528667d62").then ->
    fillIn "#password", "newpassword"
    click("form button").then ->
      equal find(".alert-success p").text(), "You can now login with your new password.", "The password reset success notice renders"
```

I'm expecting this is a user error, but I'm really stumped at the moment.

**Comment by westlywright** [comment]
@JoshSmith did you ever get this working? I've tried using @camdub solution but after i run that code the host is still the same

**Comment by lessless** [comment]
Is there a way to send CORS request through Pretender? 

```Error: Pretender will not respond to requests for URLs. It is not possible to accurately simluate the browser's CSP. Remove the https://bucket.s3.amazonaws.com from https://bucket.s3.amazonaws.com/ and try again```

**Comment by trek** [comment]
A PR for this feature is at https://github.com/trek/pretender/pull/66
