### ISSUE TITLE
Switch back to github/fetch

### ISSUE THREAD

**Issue by xg-wang** [pretenderjs/pretender#232]
Switch back to [github/fetch](https://github.com/github/fetch) once new version with UMD build release.

**Comment by cibernox** [comment]
Why the rollback?

**Comment by xg-wang** [comment]
@cibernox Not roll back, just waiting for the new release which is [TBD](https://github.com/github/fetch/issues/634)

The one being used is a forked version I submitted https://github.com/xg-wang/fetch

**Comment by cibernox** [comment]
I thought we've changed to yetch.

**Comment by xg-wang** [comment]
It was in `ember-fetch` repo. The reason we switched to Yetch is for [cancelation support](https://github.com/ember-cli/ember-fetch/issues/111). Github fetch merged the [PR](https://github.com/github/fetch/pull/592) recently, and also provided the UMD build.

**Comment by xg-wang** [comment]
Closed by https://github.com/pretenderjs/pretender/pull/235
