### ISSUE TITLE
'passthrough' missing from TypeScript Server definition in index.d.ts

### ISSUE THREAD

**Issue by jrburke** [pretenderjs/pretender#233]
When I try to use this example in a TypeScript project:

```javascript
const server = new Pretender(function() {
  this.get('/photos/:id', this.passthrough);
});
```

The TypeScript compiler complains:

```
Property 'passthrough' does not exist on type 'Server'.
```

It looks like the `export class Server` part of `index.d.ts` in this project should include a line for `passthrough`. Unfortunately I am still new to TypeScript, so at the moment I cannot suggest a precise fix.

Since it is a class declaration, I also cannot seem to use [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) to enhance the `Server` type in my project. But I could be missing something.

**Comment by ryanhollister** [comment]
unhandledRequest is missing as well.

**Comment by ohcibi** [comment]
Actually `passtrough` is defined but none of the `*Request` callbacks are.

**Comment by xg-wang** [comment]
Should have been fixed by https://github.com/pretenderjs/pretender/pull/265 and https://github.com/pretenderjs/pretender/pull/254.
Remaining typing issues are tracked in https://github.com/pretenderjs/pretender/issues/277
