### ISSUE TITLE
Restore previous UMD output

### ISSUE THREAD

**Issue by mike-north** [pretenderjs/pretender#247]
#243 from @givanse converted this project to typescript, and also created an IIFE output module.

Before cutting a 3.x release, we want to ensure that a UMD module is also exported, so that it can be easily consumed in projects such as ember-cli-pretender.

**Comment by givanse** [comment]
This PR adds an UMD output:
https://github.com/pretenderjs/pretender/pull/248

**Comment by xg-wang** [comment]
https://github.com/pretenderjs/pretender/pull/255 merged and published as 3.0.1
