### ISSUE TITLE
Missing `responseURL` property on FakeRequest

### ISSUE THREAD

**Issue by ming-codes** [pretenderjs/pretender#263]
The property is apparently used by `ember-fetch` to set `Response#url`

**Comment by xg-wang** [comment]
To clarify, is it github/fetch polyfill is using this property? https://github.com/github/fetch/blob/3674c98df696d45573750aa7873814887d25689a/fetch.js#L461

**Comment by ming-codes** [comment]
Yup, and the property is standard. https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseURL
