### ISSUE TITLE
requestBody missing from types

### ISSUE THREAD

**Issue by mfeckie** [pretenderjs/pretender#292]
https://github.com/pretenderjs/pretender/blob/master/index.d.ts#L42-L45

<img width="845" alt="Screenshot 2020-02-11 07 40 25" src="https://user-images.githubusercontent.com/1583673/74200388-c9f5db80-4ca1-11ea-8d93-6ebf79856aa5.png">

I think the 'correct' place to add it would be in `ExtraRequestData`, happy to do a PR if this is reasonable.

**Comment by xg-wang** [comment]
This should have been fixed in https://github.com/pretenderjs/FakeXMLHttpRequest/pull/48
Can you take a look what's your `fake-xml-http-request` version?
