### ISSUE TITLE
Incorrect "progress" events for requests with FormData

### ISSUE THREAD

**Issue by ghill-legwork** [pretenderjs/pretender#303]
I am trying to build a progress bar and demo / test it with Pretender. This is for a file uploader. I am wrapping the file in a FormData object before uploading: 
```
    const data = new FormData();
    data.append('file', attachedFile.file, attachedFile.file.name);
```
This all works correctly with a real server but not with Pretender. After looking into it a bit I saw that the progress events were sent fine but the event properties are incorrect. There should be two properties in the progress from which one can create a progress bar (or whatever). These are "loaded" and "total". For me they look like this: 

![Screenshot 2020-05-18 at 11 11 04](https://user-images.githubusercontent.com/58449019/82246291-429bb200-98f9-11ea-84ba-5cc8ea32b2ec.jpg)

I suspect that this is because Pretender isn't correctly reading the FormData object. In the Pretender code I see this:
```
      if (!body) {
        progressTotal = 0;
      } else {
        // Support Blob, BufferSource, USVString, ArrayBufferView
        progressTotal = body.byteLength || body.size || body.length || 0;
      }
      let progressTransmitted =
        totalTime <= 0 ? 0 : (elapsedTime / totalTime) * progressTotal;
```
https://github.com/pretenderjs/pretender/blob/b38a2b06147f5cb1105eaf7bbc79534b36e25be4/src/index.ts#L63

**Comment by xg-wang** [comment]
Some context about added support for `Support Blob, BufferSource, USVString, ArrayBufferView` mentioned in the comment you linked https://github.com/pretenderjs/pretender/pull/276
