### ISSUE TITLE
npm install fails - route-recognizer version

### ISSUE THREAD

**Issue by amirdt22** [pretenderjs/pretender#32]
Seems NPM still things you're asking for route-recognizer 0.1.1?

$ npm install pretender
npm http GET https://registry.npmjs.org/pretender
npm http 304 https://registry.npmjs.org/pretender
npm http GET https://registry.npmjs.org/fake-xml-http-request
npm http GET https://registry.npmjs.org/route-recognizer
npm http 304 https://registry.npmjs.org/fake-xml-http-request
npm http 304 https://registry.npmjs.org/route-recognizer
npm ERR! notarget No compatible version found: route-recognizer@'>=0.1.1-0 <0.2.0-0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by trek** [comment]
Handled by https://github.com/pretenderjs/pretender/pull/163
