### ISSUE TITLE
Pretender mock in Ember.js

### ISSUE THREAD

**Issue by edelsbrunner** [pretenderjs/pretender#36]
Hi, I'm trying to use Pretender to mock my server requests, but I always get this error:

```
Setup failed on something: undefined is not a function
    at Object.Pretender (http://localhost:9876/base/app/assets/vendor/components/pretender/pretender.js:12:10)
    at Object.singleModule.setup (http://localhost:9876/base/tests/specs/integration/a_routes_test.js:4:24)
    at Object.Test.setup (http://localhost:9876/base/node_modules/qunitjs/qunit/qunit.js:1276:31)
    at http://localhost:9876/base/node_modules/qunitjs/qunit/qunit.js:1460:10
    at process (http://localhost:9876/base/node_modules/qunitjs/qunit/qunit.js:1016:24)
    at http://localhost:9876/base/node_modules/qunitjs/qunit/qunit.js:186:5
 debug.html:31window.__karma__.result debug.html:31(anonymous function) adapter.js:66runLoggingCallbacks qunit.js:1167Test.finish qunit.js:1434(anonymous function) qunit.js:1469process qunit.js:1016(anonymous function)
```

After trying with my specific tests, I've tryed to do a simple test to reproduce this so I have this code:

_(code in coffeescript)_

```
singleModule "Posts",
  setup: ->
    pretender = new Pretender () ->
      @get "/posts", (request) ->
        [
          200
          {
            "Content-Type": "application/json"
          }
        ]
    return

test "something", ->
  $.get "/posts", (data) ->
    console.log data
```

The problem comes from inside of pretender.js  in Pretender(maps) function,

the maps.call(this);  or maps() is always returning **undefined**.

Do someone have a idea of what could be happening here?

Best Regards,

Marius

**Comment by lolmaus** [comment]
I've also tried to use Pretender with EmberJS and I ran into exact same issue.

By investigating the [ember-cli-pretender](https://github.com/rwjblue/ember-cli-pretender/blob/master/index.js) Ember addon I discovered that Pretender has two dependencies: FakeXMLHttpRequest and route-recognizer. They are mentioned in Pretender's `bower.json` but not in the `README`!

To resolve the Ember issue, add the following to your `ember-cli-build.js` (formerly `Brocfile.js`):

```js
  app.import('bower_components/FakeXMLHttpRequest/fake_xml_http_request.js');
  app.import('bower_components/route-recognizer/dist/route-recognizer.js');
  app.import('bower_components/pretender/pretender.js');
```

The reason why I'm not using the ember-cli-pretender addon is that it has Pretender disabled in production, implying that it's only useful for testing. But I need Pretender in production because I'm building a prototype rather than a test.

**Comment by trek** [comment]
> But I need Pretender in production because I'm building a prototype rather than a test.

You definitely don't want Pretender in production. You might want it in development, and you might deploy the development environment to remote servers though!

**Comment by lolmaus** [comment]
@trek Once again, I'm building a prototype, not a real app. By "production" I mean a production environment in EmberJS, not serving real customers. My goal is to imitate my prototype's communication with a backend without going through the hassle of coding and deploying a real backend.

I've completed the prototype, you can have a look: http://lolmaus.github.io/loadimpact-assignment/

Why is Pretender a wrong choice for that? What would you suggest using instead?

**Comment by trek** [comment]
We're talking about the same thing. I also develop like that.

**Comment by lolmaus** [comment]
@trek So is Pretender legit for my use case?

**Comment by trek** [comment]
Yep.
