### ISSUE TITLE
pretender doesn't work with jspm

### ISSUE THREAD

**Issue by faassen** [pretenderjs/pretender#54]
I just tried pretender with the jspm package manager, but there are some internals it tries that defeats jspm, in particular this line:

```
var FakeXMLHttpRequest = isNode ? require('./bower_components/FakeXMLHttpRequest/fake_xml_http_request') : window.FakeXMLHttpRequest;
```

in a jspm environment pretender thinks it's in node, but then tries to do a require directly from a ``bower_components`` directory which isn't there in a jspm setup. Since jspm is actually *not* in node the whole detection of node might also be somewhat fragile.

**Comment by trek** [comment]
Alas, this is just the current state of trying to do UMD-style support. Once https://github.com/esperantojs/esperanto supports a resolution phase I'll be rewriting everything in ES6 module format and transforming to other module formats for publication. I don't have much interest in continuing to support or evolve having a single package for all module formats.

**Comment by trek** [comment]
The env sniffing has changed significantly, not sure if this is still a problem. Feel free to reopen if it is
