### ISSUE TITLE
support for promises

### ISSUE THREAD

**Issue by aaronshaf** [pretenderjs/pretender#57]
Example:

```javascript
var server = new Pretender();
server.put('/api/songs/99', function(request) {
  return new Promise(function(resolve, reject) {
    resolve([404, {}, ""]);
  });
});
```

**Comment by trek** [comment]
I don't see what this would do. Pretender doesn't expose the return value from a handler in a public API Can you show a use case?

**Comment by aaronshaf** [comment]
My use-case would be a caching layer. When requests are made, say, to `/api/songs/99`, I want to first check localStorage or indexedDB for the data.

**Comment by trek** [comment]
Can you show code of how promises make this possible?

**Comment by aaronshaf** [comment]
The standard usage of pretender seems to require a synchronous callback. I am just going for asynchronicity. I want to intercept requests for `/foo` and return returns that I can gather from, say, IndexedDB first. 

```javascript
var server = new Pretender();
server.get('/api/songs/:id', function(request) {
  return new Promise(function(resolve, reject) {
    getSongFromIndexedDb(request.params.id).then(function(song) {
      resolve([200, {}, song])
    })
  });
});
```

**Comment by trek** [comment]
Did the `Manual` section of https://github.com/trek/pretender#timing-parameter not work for this?

**Comment by aaronshaf** [comment]
Ah, I see. While that would work, that requires keeping a reference to server handy, which doesn't seem ideal. Promises would make this much more elegant.

**Comment by trek** [comment]
PR it and I'll be better able to see

**Comment by devinrhode2** [comment]
I see some value in @aaronshaf's snippet above, namely being able to resolve the requests asynchronously. In the "extremely mediocre" node framework Hapi.js, the general pattern is:
```javascript
var handler = function(request, respond) {
  //do whatever
  setTimeout(function(){
    respond(200, {}, songJson)
  }, 2.6 * 1000);
};
```
This is infinitely more flexible and I believe would allow @aaronshaf to work in the asynchronous manner he is looking for, along with eliminating the need for a dedicated timing parameter, even though that api is pretty well done :P this would reduce the api surface as a whole

Also, nifty in that you don't really have to type more characters, except for putting "respond" as a parameter for the handler (`return [200, {}, fooJson];` -> `respond(200, {}, fooJson);`)

Though, I wonder about doing something like `return respond(200, {}, fooJson)` as to make things synchronous, in case synchronicity would be necessary? I guess it would be good to support the current api (`return [200, {}, json]`) and deprecate it if this new api were to be introduced. @trek thoughts?

**Comment by dustinfarris** [comment]
I have a use-case where I want to use graphql to process a schema, and then return the result.

http://graphql.org/docs/api-reference-graphql/#graphql

Ideally, this would look like:

```js
server.post('/graphql', (request) => {
  const { query, variables } = JSON.parse(request.requestBody);
  return graphql(Schema, query, null, variables);
});
```

but because `graphql` returns a promise, this doesn't work well with Pretender.
