### ISSUE TITLE
Using Pretender with `fetch`.

### ISSUE THREAD

**Issue by rwjblue** [pretenderjs/pretender#60]
It would be nice to be able to use `fetch` instead of `XMLHttpRequest`. When using the non-native `fetch` polyfil Pretender would likely still work (because the polyfill uses `XMLHttpRequest` to implement `fetch`), but it doesn't seem that native fetch requests would be handled by Pretender.

Spec: https://fetch.spec.whatwg.org

This issue is mostly to lay out a path forward.

/cc @cowboyd @toranb

**Comment by trek** [comment]
I'm down for it. I'd like to extend and generalize pretender to mock out several browser APIs that might seem unrelated but have to be controlled for isolated tests: xhr, fetech, geolocation, etc.

**Comment by stefanpenner** [comment]
The polyfil for fetch does use xhr https://github.com/github/fetch/blob/master/fetch.js#L263

So that buys us time until someday where native fetch can be used cross platform

**Comment by stefanpenner** [comment]
Also the ember wrapper never falls back to native fetch

**Comment by topaxi** [comment]
I tried to use pretender with fetch, but as FF and Chrome now ship fetch, this isn't working for now.

**Comment by stefanpenner** [comment]
If you use ember-fetch it will always use the polyfil (for better or worse)

**Comment by topaxi** [comment]
Oh, thx, I'll consider it :)

**Comment by trek** [comment]
I'd happily accept a PR, I just don't have a need for fetch myself right now so that work should be handled by a more vested party.

**Comment by ddcahutton** [comment]
This feels really dirty, but, to force whatwg-fetch to apply in Chrome, I did the following in the HTML I run my tests against:
```
<script>
window.fetch = undefined;
</script>
<script src="my-code-including-fetch-polyfill.js"></script>
```

**Comment by dustinfarris** [comment]
This looks interesting https://github.com/sstur/fetch-pretender
