### ISSUE TITLE
unable to npm install with pretender as dependency

### ISSUE THREAD

**Issue by jlidder** [pretenderjs/pretender#84]
I get the following error whenever i run 'npm install'. Looks like bower dependency was not installed before running the postinstall step?

npm install
npm WARN package.json assert@1.3.0 assert is also the name of a node core module.
|

> pretender@0.7.0 postinstall /Users/jlidder/Documents/repos/temp3/fba/node_modules/pretender
> bower install

sh: bower: command not found
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! pretender@0.7.0 postinstall: `bower install`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the pretender@0.7.0 postinstall script 'bower install'.
npm ERR! This is most likely a problem with the pretender package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls pretender
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jlidder/Documents/repos/temp3/wtvproject/npm-debug.log

**Comment by stefanpenner** [comment]
everything seems to be ok now (pretender@1.5.0). Lets assume this has been resolved. If not, please provide a reproduction and I can reopen.
