### ISSUE TITLE
jQuery 1.x with passthrough

### ISSUE THREAD

**Issue by code0100fun** [pretenderjs/pretender#85]
I can't get passthrough to work with jQuery 1.x. The requests are sent using `$.ajax('/path').then(...)` but the `then` callbacks are never fired.

Seems like the `onload` event is detected on the browser `xhr` but is not supported by the 1.x jQuery [`xhr`](https://github.com/jquery/jquery/blob/1.11.3/src/ajax/xhr.js) module, so it is not [dispatched](https://github.com/pretenderjs/pretender/blob/053b865064cf09dc6a07800b7a5039880381a8df/pretender.js#L168) when the response is received.

I was able to get the events to fire by removing the check for [`onload`](https://github.com/pretenderjs/pretender/blob/053b865064cf09dc6a07800b7a5039880381a8df/pretender.js#L143) and just adding both events. 

There is a chance that both events could be fired I'm guessing. Any other concerns I should check into before getting a PR ready?

**Comment by trek** [comment]
Seems bad. PR would be help.

**Comment by kottenator** [comment]
I'm using jQuery 1.x too and it doesn't work with Pretender 0.9.0
Unfortunately I can't switch to jQuery 2.x :( 
Could you (Pretender developers), please, restore jQuery 1.x support?

**Comment by olivierlesnicki** [comment]
@trek any update on this one?

**Comment by olivierlesnicki** [comment]
@code0100fun do you have a PR for this one?

**Comment by code0100fun** [comment]
I can't think of a clean way to tell when the user has an older version of jQuery without tying Pretender to jQuery in some way.

As a workaround, you may be able to wrap the [`onload`](https://github.com/pretenderjs/FakeXMLHttpRequest/blob/f48f3b8087ecb6df2ffd16ef31bd0e1bed7989f7/fake_xml_http_request.js#L144) callback of FakeXMLHTTPRequest and call `onreadystatechange`. That is what [jQuery 1.x](https://github.com/jquery/jquery/blob/1.11.3/src/ajax/xhr.js#L170) is using as a success callback.

It looks like `onreadystatechange` is supposed to be called according to the [spec](https://dvcs.w3.org/hg/xhr/raw-file/tip/Overview.html#switch-done). Maybe FakeXMLHTTPRequest should be calling `_readyStateChange ` [here](https://github.com/pretenderjs/FakeXMLHttpRequest/blob/f48f3b8087ecb6df2ffd16ef31bd0e1bed7989f7/fake_xml_http_request.js#L435), but I'm not very familiar with the internals.

Any advice @trek or @mike-north ?

**Comment by olivierlesnicki** [comment]
@code0100fun this is what i've done: https://github.com/pretenderjs/pretender/pull/114

**Comment by trek** [comment]
addressed by #130
