### ISSUE TITLE
Tests fail on master

### ISSUE THREAD

**Issue by mike-north** [pretenderjs/pretender#87]
To reproduce:
- Check out 3bec2d1df56336a784ea74ab86e70172ed7a397a (currently master, or release `0.7.0`)
- clear `node_modules` and `bower_components`, and `npm i; bower i` if you like
- run `npm test`

![screen shot 2015-07-29 at 2 46 28 pm](https://cloud.githubusercontent.com/assets/558005/8970822/ad275cfc-3600-11e5-9470-9d3f83f39296.png)

**Comment by truenorth** [comment]
Now this is happening inconsistently. Maybe related to use of setTimeout in tests?

**Comment by truenorth** [comment]
![screen shot 2015-07-29 at 2 59 58 pm](https://cloud.githubusercontent.com/assets/558005/8971115/8aaa31ca-3602-11e5-91e4-3542422805c9.png)

Trying a couple of other browsers, we can see that sometimes things pass, sometimes they fail. Getting intermittent failures across all browsers now

**Comment by EndangeredMassa** [comment]
For reference, latest (0.9.0 at this point) worked fine for me many times in many browsers.

**Comment by jerel** [comment]
I'm consistently getting 4 failing tests on master when using a ModernIE VM running IE 11.

**Comment by bantic** [comment]
@jerel What tests fail?

**Comment by jerel** [comment]
@bantic I've attached a screenshot from IE11. Note that it shows 50 tests ran instead of the 49 that are actually on master, that's only because I added one locally to try to debug #122 

![ie11](https://cloud.githubusercontent.com/assets/322706/10769528/8c8ed1b4-7cb4-11e5-99c8-b365e6dd3a70.png)

**Comment by stefanpenner** [comment]
CI suggests all is currently well
