### ISSUE TITLE
Pretender postinstall script results in strange bower install behavior

### ISSUE THREAD

**Issue by mike-north** [pretenderjs/pretender#94]
This may be a bug in NPM. @stefanpenner is going to take care of a more reasonable npm-availability approach

![screen shot 2015-08-06 at 9 43 35 am](https://cloud.githubusercontent.com/assets/558005/9117527/c099fd24-3c1f-11e5-8a1f-ad44126b1d04.png)

**Comment by stefanpenner** [comment]
working on it now.
